cloudflare:
  tunnelName: "basebandit-lab"
  tunnelId: "bf3f2a36-18d7-48c0-b876-56101fd8883d"
  secretName: "cloudflare-tunnel-creds"
  enableWarp: true
  ingress:
    - hostname: "*.infradigest.com"
      service: "https://ngx-ingress-c8r-ingress-nginx-controller.kube-system.svc.cluster.local:443"
      originRequest:
        noTLSVerify: true
resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
replicaCount: 1

